version: '3.8'

services:
  flask-app:
    image: rag-chatbot
    container_name: my-rag-chatbot
    restart: always
    network_mode: "host"
    depends_on:
      - chromadb
      - ollama
    environment:
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
    volumes:
      - ${APP_PATH}/data:/project/data

  chromadb:
    image: chromadb/chroma
    container_name: my-chromadb
    restart: always
    network_mode: "host"

  ollama:
    image: ollama/ollama
    container_name: my-ollama
    restart: always
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ${APP_PATH}/ollama_models:/root/.ollama/models

volumes:
  ollama_models:

